language: nodejs
before_script:
- npm install
- npm install -g grunt-cli
- npm install -g bower
- bower install
script:
- npm test
env:
  matrix:
  - secure: DJtzo0RYXcKHGmiCRC5PZFKu828M5OJyye5RZp/B2vhFFbpMiH/Ni+sj6N+7vuU3boX6CNvnZM+PKVz9iYleippwE6vAJk5y4Cpjo0BKeLEdn+NNW7RaOJW4EJCVmn16KTfejnk2JNpz3wH1fq98rCZmHne2zoVJFwNdjtRaslk=
